### ISSUE TITLE
Pravljenje lokalnih repozitorija

### ISSUE THREAD

**Issue by gjuwindev** [gjuwindev/GitTesting#1]
deder napravi lokalni repozitorij od ovoga GitTesting repozitorija

da vidimo kako radimo izmjene na lokalnom repozitoriju pa ih saljemo gore...

👍

**Comment by gjuwindev** [comment]
napravih lokalni repozitorij, iz komandne linije.

**Comment by isudarev** [comment]
koja oba fajla? skinuo si ova dva fajla na lokalni rep pa onda cinio izmjene i onda pushao?

**Comment by gjuwindev** [comment]
ima, ima, citajjjjjjj

-----Original Message-----

**Comment by isudarev** [comment]
da, vidim sad... zeznulo me sto iskopiram redak s krivim repositorijem i onda mi sve pokvari...

kako promijenim origin?

**Comment by isudarev** [comment]
nema veze, idem ispocetka...

**Comment by isudarev** [comment]
jeeeeesam :)))

**Comment by isudarev** [comment]
dakle, ako sam dobro zapamtila:

-	napravi folder na D:
-	git init
-	git remote add origin https://github.com/gjuwindev/GitTesting
-	git pull origin master
          o	povuce sve fajlove s online rep
-	izmjeni nesto u fajlu
          o	save
          o	stage (+)
          o	commit
-	git push -u origin master

right?

**Comment by gjuwindev** [comment]
mozes reci i "git init <ime foldera>"

propustila si navesti i "cd <ime foldera>"

jest, ostalo bih rekao da je sve barem odlicno :-)

**Comment by gjuwindev** [comment]
odnosno u VS code napravis novi folder, inicijaliziras i napravis CLONE...  izmijenis pa napravis RECYCLE

**Comment by gjuwindev** [comment]
fino, cini se da znamo napraviti lokalne repozitorije...
